# use image
FROM python:2.7.13

# copy the code to the container
ADD ./sources/*.py ./configuration.json ./pip_requirements_reddit_monitor /sources/
WORKDIR /sources/

# run configuration
RUN pip install -r pip_requirements_reddit_monitor

# start script
CMD [ "python", "/sources/reddit_monitor.py" ]
